name: ipywidgets-bokeh-CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x]
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upgrade npm
        shell: bash
        run: |
          npm install --location=global npm

      - name: Install JavaScript dependencies
        working-directory: ./ipywidgets_bokeh
        shell: bash
        run: |
          npm ci --no-progress

      - name: Build ipywidgets-bokeh JavaScript
        working-directory: ./ipywidgets_bokeh
        shell: bash
        run: |
          npm run build

      - name: Run JavaScript tests
        if: success() || failure()
        working-directory: ./ipywidgets_bokeh
        shell: bash
        run: |
          npm run test

      - name: Lint the JavaScript codebase
        if: success() || failure()
        working-directory: ./ipywidgets_bokeh
        shell: bash
        run: |
          npm run lint

      - name: Install dev Python dependencies
        if: success() || failure()
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --editable .[dev]
          python -m playwright install --with-deps ${{ matrix.browser }}

      - name: Run Playwright & Python tests
        if: success() || failure()
        shell: bash
        run: |
          pytest

      - name: Check repository status
        if: success() || failure()
        shell: bash
        run: |
          OUTPUT=$(git status --short .)
          if [[ ! -z "$OUTPUT" ]]; then echo $OUTPUT; exit 1; fi
